SELECT * FROM EMP
SELECT ENAME, DEPTNO, HIREDATE FROM EMP WHERE CONVERT(DATETIME,HIREDATE,0)<'1982'
SELECT ENAME FROM EMP WHERE JOB='MANAGER' AND DEPTNO=20
SELECT ENAME +': 1 Month Salary = '+ CAST(SAL AS varchar(50)) AS DETAILS FROM EMP


LAB 2
SELECT ENAME FROM EMP WHERE COMM IS NULL
SELECT ENAME, DEPTNO,HIREDATE FROM EMP WHERE CONVERT(DATETIME,HIREDATE,0)='1982'
SELECT ENAME FROM EMP WHERE ENAME LIKE '%LL%' AND DEPTNO=30 OR MGR=7782
SELECT ENAME, JOB, DEPTNO, HIREDATE FROM EMP WHERE JOB='CLERK' AND DEPTNO IN(10, 20) AND CONVERT(DATETIME,HIREDATE,0)<'1983'
SELECT ENAME, SAL FROM EMP WHERE SAL NOT BETWEEN 1500 AND 2850
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > (SAL + (SAL*0.1))


LAB 3
SELECT E.ENAME, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.COMM IS NOT NULL
SELECT W.ENAME + ' WORKS FOR ' + (M.ENAME ) FROM EMP W, EMP M WHERE ISNULL(W.MGR, W.EMPNO)=M.EMPNO
SELECT W.ENAME FROM EMP W, EMP E WHERE E.ENAME='KING' AND W.MGR=E.EMPNO
SELECT DISTINCT E.JOB, E.DEPTNO, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.DEPTNO=30
SELECT E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC='DALLAS'
SELECT W.ENAME  AS Employee, W.EMPNO AS Emp#, M.ENAME AS Manager, M.EMPNO AS Manger# FROM EMP W, EMP M WHERE ISNULL(W.MGR, W.EMPNO)=M.EMPNO