--SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP) ORDER BY SAL DESC

--SELECT ENAME,SAL FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='KING')

--SELECT DEPTNO, ENAME, JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES')

--SELECT ENAME, HIREDATE, SAL FROM EMP WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME='SCOTT') AND COMM = (SELECT COMM FROM EMP WHERE ENAME='SCOTT')

--SELECT ENAME, DEPTNO, JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS')

--(SELECT EMPNO FROM EMP WHERE JOB <> 'ANALYST') INTERSECT (SELECT EMPNO FROM EMP)

--SELECT ENAME, HIREDATE FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'BLAKE') AND ENAME <> 'BLAKE'

--SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP) AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%T%'  )